# applications/harbor-stack.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USER/harbor-scanning-system.git
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://10.28.99.189:7443
    namespace: harbor-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
